title: I’m starving, how long is dinner gonna take?
description: A multiple linear regression approach to predicting the number of minutes needed to make your dinner.
author: Malik Alabbas
email: alabbas@umich.com
theme: minima

sass:
  load_paths:
    - _sass/minima
    - _sass

include:
  - head-custom.html

# Enable the dark skin
minima:
  skin: dark

